title: <p align="center"> Varjit Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="Varjit Gupta_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/varjit-gupta-35750819/">LinkedIn</a> |
  <a href="https://github.com/varjit">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time healtcare equipment data.
  Worked Numantra Technologies for companies like Bayer,Philips in Data Analytics team.
  Working Healthcare Domain for 6 years.
  <br>
  </p>



theme: jekyll-theme-minimal
